# This is a basic workflow to help you get started with Actions

name: Run Create Template

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  pull_request:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  repo: ${{ github.event.repository.name }}
  env_path: /mnt/env
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Mske executable Create Template
        run: chmod +x $env_path/$repo/create-template.sh

      - name: Run Create Template
        run: $env_path/$repo/create-template.sh $env_path/$repo/.env
